name: Benchmark Minimal Scan Example 
on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run minimal steps to run github-action-benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.10'
      - name: Run benchmark
        run: cd BENCHMARKING && julia --project=.. bench_julia.jl 

      - name: Store Benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Julia benchmark result
          tool: 'julia'
          output-file-path: BENCHMARKING/output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true

          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@irslushy'
